#/bin/sh
date
/MYSQL/mysql/bin/mysql -h 127.0.0.1 -uupm -pupm?4321? pm << EOF
DELETE FROM T_PM_PUSH_DEAL WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PM_API_REQUEST_LOG WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY REQUEST_SEQ ASC;
DELETE FROM T_PG_IF_00 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_01 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_02 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_03 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_04 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_05 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_06 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_07 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_08 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
DELETE FROM T_PG_IF_09 WHERE REG_DATETIME < DATE_FORMAT(DATE_ADD(NOW(), INTERVAL - 10 MINUTE),'%Y-%m-%d %H:%i:00') ORDER BY IF_ID ASC;
EOF
